# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.MyName.com
title: Chris Allen
email: calle027@ucr.edu
author: Chris Allen
description: "Chris Allen's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
plugins:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/Calle027
  - icon: envelope-o
    title: email
    url: mailto:calle027@ucr.edu
  #- icon: linkedin
 #   title: linkedin
#    url: https://www.linkedin.com/in/NyName/
#  - icon: file-pdf-o
#    title: CV
#    url: img/MyCV.pdf
#  - icon: twitter
 #   title: twitter
  #  url: https://twitter.com/MyName

